### ISSUE TITLE
Backend Qt5Agg is interactive backend. Turning interactive mode on.

### ISSUE THREAD

**Issue by sxmafei** [babysor/Realtime-Voice-Clone-Chinese#39]
直接运行没有问题，但是debug demo_toolbox.py时 报错：
Traceback (most recent call last):
  File "D:\work\python\ide\pycharm\PyCharm 2020.1.2\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\work\python\ide\pycharm\PyCharm 2020.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/instance/tts/Realtime-Voice-Clone-Chinese-main/demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "E:\instance\tts\Realtime-Voice-Clone-Chinese-main\toolbox\__init__.py", line 75, in __init__
    self.ui = UI()
  File "E:\instance\tts\Realtime-Voice-Clone-Chinese-main\toolbox\ui.py", line 450, in __init__
    self.projections_layout.addWidget(FigureCanvas(fig))
TypeError: addWidget(self, QWidget, stretch: int = 0, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 1 has unexpected type 'FigureCanvasQTAgg'
Backend Qt5Agg is interactive backend. Turning interactive mode on.

**Comment by sxmafei** [comment]
环境问题，将python从3.7 换成3.8 后解决了
